In [57]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [58]:
# load the data and display the first few rows
df = pd.read_csv('../../data/train-test.csv')
df.head()

,load_id,pickup,delivery,pickup_lat,pickup_lon,delivery_lat,delivery_lon,distance,equipment,weight,date,market_index,quote_signal,posted_rate
0,TR-000001,Richmond,Baltimore,38.09122,-76.78906,38.16908,-72.74564,274.3,Dry Van,30658.0,2025-01-01,0.95684,2.39595,645.41
1,TR-000002,Richmond,Philadelphia,38.09122,-76.78906,39.22317,-72.96710,280.5,Reefer,17555.0,2025-01-01,0.97623,2.43355,679.97
2,TR-000003,Philadelphia,Green Bay,39.22317,-72.96710,44.30296,-87.52871,967.8,Dry Van,31721.0,2025-01-01,1.00971,1.84491,1802.54
3,TR-000004,Hartford,Atlanta,39.55328,-72.18051,34.84933,-86.28940,965.4,Dry Van,32333.0,2025-01-01,0.94518,1.87712,1827.28
4,TR-000005,Dallas,Nashville,31.83025,-94.38343,35.29479,-88.08915,541.9,Reefer,35183.0,2025-01-01,0.98480,2.56300,1380.28

In [59]:
# describe the dataset to get a summary of statistics for each column
df.describe()

,pickup_lat,pickup_lon,delivery_lat,delivery_lon,distance,weight,market_index,quote_signal,posted_rate
count,48000.000000,48000.000000,48000.000000,48000.000000,48000.000000,47700.000000,47626.000000,48000.000000,48000.000000
mean,35.647545,-90.928964,35.641175,-90.857310,1135.856654,31028.844004,1.083387,2.062468,2373.980682
std,4.315285,13.482431,4.317199,13.476589,728.564416,9391.440620,0.168091,0.291391,1486.493245
min,28.357650,-121.698490,28.357650,-121.698490,70.000000,-47500.000000,0.676390,0.692280,57.220000
25%,31.986910,-98.400590,31.986910,-98.400590,550.400000,25800.000000,0.949670,1.891030,1251.555000
50%,35.294790,-88.089150,35.294790,-87.528710,953.300000,31436.500000,1.055800,2.055750,2030.760000
75%,39.411040,-83.285060,39.411040,-83.285060,1645.525000,37018.000000,1.219590,2.221685,3330.750000
max,44.302960,-69.500000,44.302960,-69.500000,3439.800000,47500.000000,1.467780,3.610350,25533.000000

In [60]:
# get information about the dataset, including the number of non-null values and data types for each column
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48000 entries, 0 to 47999
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   load_id       48000 non-null  object
 1   pickup        48000 non-null  object
 2   delivery      48000 non-null  object
 3   pickup_lat    48000 non-null  float64
 4   pickup_lon    48000 non-null  float64
 5   delivery_lat  48000 non-null  float64
 6   delivery_lon  48000 non-null  float64
 7   distance      48000 non-null  float64
 8   equipment     48000 non-null  object
 9   weight        47700 non-null  float64
 10  date          48000 non-null  object
 11  market_index  47626 non-null  float64
 12  quote_signal  48000 non-null  float64
 13  posted_rate   48000 non-null  float64
dtypes: float64(9), object(5)
memory usage: 5.1+ MB

we found 300 values null in weight col and 374 values null in market index

we will handle them by filling it with the mean of each col

In [61]:
# select only the float64 columns from the dataframe to fill the null values with the mean of each column
df_float = df.select_dtypes(include=['float64'])
df_float.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48000 entries, 0 to 47999
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   pickup_lat    48000 non-null  float64
 1   pickup_lon    48000 non-null  float64
 2   delivery_lat  48000 non-null  float64
 3   delivery_lon  48000 non-null  float64
 4   distance      48000 non-null  float64
 5   weight        47700 non-null  float64
 6   market_index  47626 non-null  float64
 7   quote_signal  48000 non-null  float64
 8   posted_rate   48000 non-null  float64
dtypes: float64(9)
memory usage: 3.3 MB

In [62]:
float_cols = df_float.columns
df[float_cols] = df_float.fillna(df_float.mean())

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48000 entries, 0 to 47999
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   load_id       48000 non-null  object
 1   pickup        48000 non-null  object
 2   delivery      48000 non-null  object
 3   pickup_lat    48000 non-null  float64
 4   pickup_lon    48000 non-null  float64
 5   delivery_lat  48000 non-null  float64
 6   delivery_lon  48000 non-null  float64
 7   distance      48000 non-null  float64
 8   equipment     48000 non-null  object
 9   weight        48000 non-null  float64
 10  date          48000 non-null  object
 11  market_index  48000 non-null  float64
 12  quote_signal  48000 non-null  float64
 13  posted_rate   48000 non-null  float64
dtypes: float64(9), object(5)
memory usage: 5.1+ MB

In [64]:
df.sum().isnull()

load_id         False
pickup          False
delivery        False
pickup_lat      False
pickup_lon      False
delivery_lat    False
delivery_lon    False
distance        False
equipment       False
weight          False
date            False
market_index    False
quote_signal    False
posted_rate     False
dtype: bool

In [65]:
df.describe(include='all')

,load_id,pickup,delivery,pickup_lat,pickup_lon,delivery_lat,delivery_lon,distance,equipment,weight,date,market_index,quote_signal,posted_rate
count,48000,48000,48000,48000.000000,48000.000000,48000.000000,48000.000000,48000.000000,48000,48000.000000,48000,48000.000000,48000.000000,48000.000000
unique,48000,64,64,NaN,NaN,NaN,NaN,NaN,3,NaN,304,NaN,NaN,NaN
top,TR-000001,Oklahoma City,Lexington,NaN,NaN,NaN,NaN,NaN,Dry Van,NaN,2025-06-17,NaN,NaN,NaN
freq,1,1242,1197,NaN,NaN,NaN,NaN,NaN,27202,NaN,198,NaN,NaN,NaN
mean,NaN,NaN,NaN,35.647545,-90.928964,35.641175,-90.857310,1135.856654,NaN,31028.844004,NaN,1.083387,2.062468,2373.980682
std,NaN,NaN,NaN,4.315285,13.482431,4.317199,13.476589,728.564416,NaN,9362.045754,NaN,0.167435,0.291391,1486.493245
min,NaN,NaN,NaN,28.357650,-121.698490,28.357650,-121.698490,70.000000,NaN,-47500.000000,NaN,0.676390,0.692280,57.220000
25%,NaN,NaN,NaN,31.986910,-98.400590,31.986910,-98.400590,550.400000,NaN,25835.750000,NaN,0.950610,1.891030,1251.555000
50%,NaN,NaN,NaN,35.294790,-88.089150,35.294790,-87.528710,953.300000,NaN,31367.000000,NaN,1.057625,2.055750,2030.760000
75%,NaN,NaN,NaN,39.411040,-83.285060,39.411040,-83.285060,1645.525000,NaN,36985.000000,NaN,1.218525,2.221685,3330.750000
max,NaN,NaN,NaN,44.302960,-69.500000,44.302960,-69.500000,3439.800000,NaN,47500.000000,NaN,1.467780,3.610350,25533.000000

by filling the null values with null we see there is no difference in the statistics of each feature

In [66]:
# Display all duplicate rows
df[df.duplicated()]

Empty DataFrame
Columns: [load_id, pickup, delivery, pickup_lat, pickup_lon, delivery_lat, delivery_lon, distance, equipment, weight, date, market_index, quote_signal, posted_rate]
Index: []

No duplicate values

In [67]:
df["date"] = pd.to_datetime(df["date"])

# 2. Extract Standard Tabular Features (Great for XGBoost / Random Forest)
df["year"] = df["date"].dt.year
df["month"] = df["date"].dt.month
df["day"] = df["date"].dt.day
df["day_of_week"] = df["date"].dt.dayofweek  # 0 = Monday, 6 = Sunday
df["day_of_year"] = df["date"].dt.dayofyear
df["quarter"] = df["date"].dt.quarter
df["is_weekend"] = df["day_of_week"].isin([5, 6]).astype(int)

# 3. Extract Cyclical Encodings (Great for Neural Networks / Linear Models)
# Encode Month (T = 12)
df["month_sin"] = np.sin(2 * np.pi * df["month"] / 12)
df["month_cos"] = np.cos(2 * np.pi * df["month"] / 12)

# Encode Day of Week (T = 7)
df["dow_sin"] = np.sin(2 * np.pi * df["day_of_week"] / 7)
df["dow_cos"] = np.cos(2 * np.pi * df["day_of_week"] / 7)

# Encode Day of Year (T = 365)
df["doy_sin"] = np.sin(2 * np.pi * df["day_of_year"] / 365)
df["doy_cos"] = np.cos(2 * np.pi * df["day_of_year"] / 365)

# View a selection of the newly generated features
print(
    df[
        [
            "load_id",
            "date",
            "day_of_week",
            "is_weekend",
            "month_sin",
            "month_cos",
        ]
    ]
)

         load_id       date  day_of_week  is_weekend  month_sin  month_cos
0      TR-000001 2025-01-01            2           0   0.500000   0.866025
1      TR-000002 2025-01-01            2           0   0.500000   0.866025
2      TR-000003 2025-01-01            2           0   0.500000   0.866025
3      TR-000004 2025-01-01            2           0   0.500000   0.866025
4      TR-000005 2025-01-01            2           0   0.500000   0.866025
...          ...        ...          ...         ...        ...        ...
47995  TR-047996 2025-10-31            4           0  -0.866025   0.500000
47996  TR-047997 2025-10-31            4           0  -0.866025   0.500000
47997  TR-047998 2025-10-31            4           0  -0.866025   0.500000
47998  TR-047999 2025-10-31            4           0  -0.866025   0.500000
47999  TR-048000 2025-10-31            4           0  -0.866025   0.500000

[48000 rows x 6 columns]

In [68]:
# convert categorical columns to numerical using one-hot encoding
df = pd.get_dummies(df, columns=["pickup", "delivery", "equipment"], drop_first=True, dtype=int)

In [69]:
df.head()

,load_id,pickup_lat,pickup_lon,delivery_lat,delivery_lon,distance,weight,date,market_index,quote_signal,...,delivery_Shreveport,delivery_St. Louis,delivery_Syracuse,delivery_Tampa,delivery_Toledo,delivery_Tucson,delivery_Tulsa,delivery_Washington,equipment_Flatbed,equipment_Reefer
0,TR-000001,38.09122,-76.78906,38.16908,-72.74564,274.3,30658.0,2025-01-01,0.95684,2.39595,...,0,0,0,0,0,0,0,0,0,0
1,TR-000002,38.09122,-76.78906,39.22317,-72.96710,280.5,17555.0,2025-01-01,0.97623,2.43355,...,0,0,0,0,0,0,0,0,0,1
2,TR-000003,39.22317,-72.96710,44.30296,-87.52871,967.8,31721.0,2025-01-01,1.00971,1.84491,...,0,0,0,0,0,0,0,0,0,0
3,TR-000004,39.55328,-72.18051,34.84933,-86.28940,965.4,32333.0,2025-01-01,0.94518,1.87712,...,0,0,0,0,0,0,0,0,0,0
4,TR-000005,31.83025,-94.38343,35.29479,-88.08915,541.9,35183.0,2025-01-01,0.98480,2.56300,...,0,0,0,0,0,0,0,0,0,1

In [70]:
columns_to_drop = ["load_id", "pickup_lat", "pickup_lon", "delivery_lat", "delivery_lon"
                   , "month_sin", "month_cos", "dow_sin", "dow_cos", "doy_sin", "doy_cos"]
df.drop(columns=columns_to_drop, inplace=True)

In [71]:
df["date"] = pd.to_datetime(df["date"])

train_df = df[df["date"] < "2025-09-01"].copy()

X_train = train_df.drop(columns=["posted_rate", "date"])
y_train = train_df["posted_rate"]

valid_df = df[
    (df["date"] >= "2025-09-01") &
    (df["date"] < "2025-10-01")
].copy()
valid_df = valid_df.drop(columns=["date"])

test_df = df[
    (df["date"] >= "2025-10-01") &
    (df["date"] < "2025-11-01")
].copy()
X_test = test_df.drop(columns=["posted_rate", "date"])
y_test = test_df["posted_rate"]

print(train_df.shape)
print(valid_df.shape)
print(test_df.shape)

(38477, 141)
(4670, 140)
(4853, 141)

In [72]:
df.head()

,distance,weight,date,market_index,quote_signal,posted_rate,year,month,day,day_of_week,...,delivery_Shreveport,delivery_St. Louis,delivery_Syracuse,delivery_Tampa,delivery_Toledo,delivery_Tucson,delivery_Tulsa,delivery_Washington,equipment_Flatbed,equipment_Reefer
0,274.3,30658.0,2025-01-01,0.95684,2.39595,645.41,2025,1,1,2,...,0,0,0,0,0,0,0,0,0,0
1,280.5,17555.0,2025-01-01,0.97623,2.43355,679.97,2025,1,1,2,...,0,0,0,0,0,0,0,0,0,1
2,967.8,31721.0,2025-01-01,1.00971,1.84491,1802.54,2025,1,1,2,...,0,0,0,0,0,0,0,0,0,0
3,965.4,32333.0,2025-01-01,0.94518,1.87712,1827.28,2025,1,1,2,...,0,0,0,0,0,0,0,0,0,0
4,541.9,35183.0,2025-01-01,0.98480,2.56300,1380.28,2025,1,1,2,...,0,0,0,0,0,0,0,0,0,1

In [76]:
from sklearn.ensemble import ExtraTreesRegressor
from sklearn.feature_selection import SelectFromModel

# X_train, y_train, X_valid, X_test must already exist
# Ensure posted_rate and load_id are not inside X_*

selector_model = ExtraTreesRegressor(
    n_estimators=300,
    min_samples_leaf=2,
    max_features=0.8,
    random_state=42,
    n_jobs=-1
)

selector = SelectFromModel(
    estimator=selector_model,
    threshold="median"   # keeps approximately the top 50% by importance
)

# Learn important features from training data only
selector.fit(X_train, y_train)

selected_features = X_train.columns[selector.get_support()].tolist()

print("Original features:", X_train.shape[1])
print("Selected features:", len(selected_features))
print(selected_features)

Original features: 139
Selected features: 70
['distance', 'weight', 'market_index', 'quote_signal', 'month', 'day', 'day_of_week', 'day_of_year', 'quarter', 'is_weekend', 'pickup_Albuquerque', 'pickup_Atlanta', 'pickup_Bakersfield', 'pickup_Baltimore', 'pickup_Baton Rouge', 'pickup_Boston', 'pickup_Buffalo', 'pickup_Charleston', 'pickup_Dallas', 'pickup_El Paso', 'pickup_Fort Wayne', 'pickup_Fresno', 'pickup_Green Bay', 'pickup_Greensboro', 'pickup_Hartford', 'pickup_Kansas City', 'pickup_Lexington', 'pickup_Los Angeles', 'pickup_Mobile', 'pickup_Montgomery', 'pickup_Oklahoma City', 'pickup_Phoenix', 'pickup_Providence', 'pickup_Reno', 'pickup_Richmond', 'pickup_Tucson', 'pickup_Washington', 'delivery_Amarillo', 'delivery_Atlanta', 'delivery_Bakersfield', 'delivery_Baltimore', 'delivery_Baton Rouge', 'delivery_Boston', 'delivery_Buffalo', 'delivery_Charleston', 'delivery_Cincinnati', 'delivery_Fort Wayne', 'delivery_Fresno', 'delivery_Harrisburg', 'delivery_Hartford', 'delivery_Jacksonville', 'delivery_Little Rock', 'delivery_Los Angeles', 'delivery_Lubbock', 'delivery_Memphis', 'delivery_Milwaukee', 'delivery_Mobile', 'delivery_Nashville', 'delivery_Oklahoma City', 'delivery_Philadelphia', 'delivery_Phoenix', 'delivery_Raleigh', 'delivery_Reno', 'delivery_San Antonio', 'delivery_Savannah', 'delivery_Shreveport', 'delivery_Syracuse', 'delivery_Tucson', 'equipment_Flatbed', 'equipment_Reefer']